version: "3.9"

services:
  twitter-db:
    image: postgres:17
    container_name: twitter-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - twitter_db_data:/var/lib/postgresql/data
    networks:
      - twitter-net

  twitter-rabbit:
    image: rabbitmq:3-management
    container_name: twitter-rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
    networks:
      - twitter-net

  twitter-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter-backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - twitter-db
      - twitter-rabbit
    networks:
      - twitter-net
      - proxy

networks:
  twitter-net:
  proxy:
    external: true

volumes:
  twitter_db_data: