version: "3.9"

services:
  twitter-frontend:
    image: node:22.15.0
    container_name: twitter-frontend
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run build && npx serve -s build -l 8081"
    ports:
      - "8081:8081"
    networks:
      - proxy
      - twitter-net

  twitter-db:
    image: postgres:17
    container_name: twitter-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - twitter_db_data:/var/lib/postgresql/data
    networks:
      - twitter-net

  twitter-rabbit:
    image: pcloud/rabbitmq-stomp:latest
    container_name: twitter-rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"    # AMQP for Spring
      - "15672:15672"  # RabbitMQ manager
      - "61613:61613"  # STOMP
    volumes:
      - twitter-rabbit-data:/var/lib/rabbitmq/mnesia
    networks:
      - twitter-net

  twitter-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - twitter-db
      - twitter-rabbit
    ports:
      - "8082:8082"
    networks:
      - twitter-net
      - proxy

networks:
  twitter-net:
  proxy:
    external: true

volumes:
  twitter_db_data:
    external: false
  twitter-rabbit-data:
    external: false