version: '3'
services:
  postgres:
    image: postgres:17
    container_name: 'postgres_17'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=twitter
    ports:
      - 5432:5432
    volumes:
      - postgresqldata17:/var/lib/postgresql/data
  rabbitmq:
    image: pcloud/rabbitmq-stomp:latest
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia
  node-mailer:
    image: vpodhornyi/node-mailer:latest
    container_name: 'node-mailer'
    ports:
      - 587:587
      - 8081:8081
volumes:
  postgresqldata17:
  rabbitmq-data:

